services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 6pdmR3rqEs3Wl0mhJzCj
      POSTGRES_DB: vpn_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3003:3000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
